export const products = [
  {
    id:   'panel-led-100w',
    name: 'Panel LED 100W',
    price: '70000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-200w',
    name: 'Panel LED 200W',
    price: '90000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-300w',
    name: 'Panel LED 300W',
    price: '130000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-360w',
    name: 'Panel LED 360W',
    price: '80000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-400w',
    name: 'Panel LED 400W',
    price: '165000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-500w',
    name: 'Panel LED 500W',
    price: '180000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-600w',
    name: 'Panel LED 600W',
    price: '195000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-640w',
    name: 'Panel LED 640W',
    price: '120000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-mixto-100w',
    name: 'Panel LED Mixto 100W',
    price: '110000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-mixto-200w',
    name: 'Panel LED Mixto 200W',
    price: '140000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-mixto-300w',
    name: 'Panel LED Mixto 300W',
    price: '195000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-mixto-400w',
    name: 'Panel LED Mixto 400W',
    price: '245000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-mixto-500w',
    name: 'Panel LED Mixto 500W',
    price: '265000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'panel-led-mixto-600w',
    name: 'Panel LED Mixto 600W',
    price: '320000',
    type: 'iluminacion',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'carpa-60x60x160',
    name: 'Carpa 60x60cm x1.60m',
    price: '70000',
    type: 'carp',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'carpa-70x70x180',
    name: 'Carpa 70x70cm x1.80m',
    price: '80000',
    type: 'carp',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'carpa-80x80x180',
    name: 'Carpa 80x80cm x1.80m',
    price: '90000',
    type: 'carp',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'carpa-1x1x2',
    name: 'Carpa 1x1x2m',
    price: '110000',
    type: 'carp',
    img: "/src/assets/lamparaprueba.webp",
  },
  {
    id:   'carpa-1.20x1.20x2',
    name: 'Carpa 1.20x1.20x2m',
    price: '150000',
    type: 'carp',
    img: "/src/assets/lamparaprueba.webp",
  },
]